# Demonstration and testing purposes only #

[ISSUER]
attestation_of_reserve = "https://blocktransfer.com/board-resolutions/demo.pdf"
# affiliate_selling = false
bt_company_code = "DEMO"
blue_sky = { reg_states = ["NC", "GA", "NY", "DE", "FL"], exchange = "None" }
cik = 0
conditions = "Fully paid and non-assessable shares."
corporate_affiliations = []
cusip = ""
display_decimals = 7
desc.main = "Example Company is used interally for product demos and development."
desc.business = "Manufacturing and distribution of widgets."
desc.facilities = "Remote-first business with shared offices in Atlanta, GA."
desc.products = "Sells widgets."
ein = 123456789
highest_curr_solicitation = "Reg D"
intra_state = false
ir.email = ""
ir.phone = ""
jurisdiction = "Delaware, US"
latest_financial_balance_sheet = "https://blocktransfer.info/DEMO/financial-reports/current/annual.pdf"
latest_PNL_and_retained_earnings = "https://blocktransfer.info/DEMO/financial-reports/current/quarterly.pdf"
lockout_period = ["12-31->4-15"]
min_reg_d_506c_state_init_usd = "5000"
meetings = { 2023 = "2023-4-29" , 2024 = "endCountProxyVotesDate", 2024a = "2024-7-8" }
name = "Example Security Inc."
name_previous = ["Alias 1 (DE)", "Alias 2 (DE)", "Alias 3 Inc (WY)"]
over_10M_assets = false
principal_executive_office = "123 Main Street, Atlanta, GA 30000"
principal_place_of_business = "123 Main Street, Atlanta, GA 30000"
redemption_instructions = "Send your shares to cede*blocktransfer.io and initiate a request from your legacy broker."
registration_effective = false
reporting_company = false
req_bt_506b_ppm = false
shell_company = false
sic = 7374
transfer_agent = "BlockTrans Syndicate (99 Wall St #4640, New York, NY 10005)"

[[INSIDERS]]
name = "John Doe"
title = "CEO"

[[INSIDERS]]
name = "Matt Smith"
title = "CFO"

[[STOCKS]]
authorized = 100000000
code = "DEMO"
class = "A"
class_type = "common"
convertible = ""
dividend = "None planned."
image = "https://blocktransfer.com/imgs/demo.png"
outstanding_EOY = { 2023-12-31 = 3248903 }
par = "$0.001"
preference = "Lowest"
splits_effective = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2->1 effective 2022-1-1"
status = "test"
votes_per_share = 1

[[STOCKS]]
authorized = 70000
code = "DEMOP"
class = "B"
class_type = "preffered"
convertible = "1->42 convertable to Class A."
dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
image = "https://blocktransfer.com/imgs/demo.png"
outstanding_EOY = { 2023-12-31 = 3248903 }
par = "$0.001"
preference = "Above A, below debt."
rights = "Same rights as 42 shares of Class A common stock, except for the voting rights of 10 Class A shares."
splits_effective = { eff_2021-4-20 = "1->5", 2021-10-9 = "3->2", 2022-1-1 = "2->1" }
status = "test"
votes_per_share = 10

[[STOCKS]]
authorized = 70000
code = "DEMOA1"
class = "C"
class_type = "common"
convertible = "1->1 convertable to class A upon exchange listing."
dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
image = "https://blocktransfer.com/imgs/demo.png"
outstanding_EOY = { 2023-12-31 = 3248903 }
par = "$0.001"
preference = "Above A, below debt."
rights = "A share of Class B preffered stock has the rights of 1500 shares of Class A common stock, except that a Class B share has the voting rights of 10 Class A shares."
# reg_A_tier_2_yr_1_affiliated_sales_max_usd = "" -- todo: simplify reg a resales
splits_effective = { 2021-4-20 = "1->5", 2021-10-9 = "3->2", 2022-1-1 = "2->1" }
status = "test"
votes_per_share = 1

[[BONDS]]
code = "DEMOX1"
convertible = false
coupon = "2.95"
image = "https://blocktransfer.com/imgs/demo.png"
maturity = "2023-10-4"
outstanding_EOY = { 2023-12-31 = 3248903 }
par = ""
preference = ""
puttable = ""
status = "test"
