[[CURRENCIES]]
code = "DEMO"
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
status = "test"
display_decimals = 7
name = "Example Security"
desc = "This is an example stock used interally for product demos and development."
conditions = "Register at investors.blocktransfer.io for applicable terms."
image = "https://blocktransfer.io/img/demo.png"
is_unlimited = true
is_asset_anchored = true
anchor_asset_type = "stock"
anchor_asset = "922908355-test"
attestation_of_reserve = "https://blocktransfer.io/board-resolutions/demo.pdf"
redemption_instructions = "Submit a DWAC transfer request to/from DRS through your broker."
regulated = false
splits = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2 to 1 effective 2022-1-1"
