[ISSUER]
attestation_of_reserve = "https://blocktransfer.io/board-resolutions/demo.pdf"
company_code = "DEMO"
cik = 0
conditions = "Fully paid and non-assessable shares."
cusip = ""
display_decimals = 7
desc = "Example Company is used interally for product demos and development."
effective_registration = false
ein = 123456789
name = "Example Security Inc."
org_jurisdiction = "Delaware, United States"
principal_office = "123 Main Street, Atlanta, GA 30000"
redemption_instructions = "($75 fee) Send your shares to cede*blocktransfer.io and initiate a request from your legacy broker."
reporting_company = false

[[STOCKS]]
authorized = 100000000
code = "DEMO"
class = "A"
class_type = "common"
image = "https://blocktransfer.io/imgs/demo.png"
par = "$0.001"
splits = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2 to 1 effective 2022-1-1"
status = "test"
votes_per_share = 1

[[STOCKS]]
authorized = 70000
code = "DEMO-B"
class = "B"
class_type = "preffered"
display_decimals = 7
image = "https://blocktransfer.io/imgs/demo.png"
par = "$0.001"
splits = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2 to 1 effective 2022-1-1"
status = "test"
votes_per_share = 10
